version: '3.8'

services:
  front-devsecops:
    build:
      context: .
      dockerfile: Dockerfile
    image: niko085/pep2devsecops_frontend2
    container_name: pep2devsecops_frontend2
    ports:
      - "3000:80"
    restart: always